---
# tasks file for ansible-role-deploy_firewall

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Include package specific tasks.
  ansible.builtin.include_tasks: '{{ dpfw_firewall_type }}.yml'
