---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Include variables.
      ansible.builtin.include_vars: 'vars/main.yml'

    - name: Update apt cache.
      ansible.builtin.package:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

  roles:
    - role: glillico.deploy_firewall
